"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
[](bg:surface1 fg:surface0)\
$directory\
[](fg:surface1 bg:sapphire)\
$git_branch\
$git_status\
[](fg:sapphire bg:red)\
$python\
$sudo\
[](fg:red bg:purple)\
[](fg:purple)\
$line_break$character"""

right_format = """
$cmd_duration\
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = " "

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:blue bg:surface1"
read_only_style = "fg:blue bg:surface1"
read_only = " "
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 8
truncate_to_repo = true
truncation_symbol = "../"
home_symbol = " "

[sudo]
style = 'fg:base bg:red'
symbol = ' '
disabled = true
format = "[$symbol]($style)"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = "󰥥"
"Music" = ""
"Pictures" = ""

[cmd_duration]
min_time = 500
style = "fg:text bg:surface0 bold"
format = '[](surface0)[$duration⌛]($style)[](fg:surface0)'

[git_branch]
symbol = ""
style = "bg:red"
format = '[[ $symbol $branch ](fg:base bg:sapphire)]($style)'

[git_status]
style = "bg:red"
format = '[[($all_status$ahead_behind )](fg:base bg:sapphire)]($style)'
conflicted = " $count "
untracked = " $count "
modified = " $count "
deleted = " $count "
staged = " $count "
renamed = " $count "
stashed = " $count "


[c]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[rust]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[python]
symbol = " "
disabled = false
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'
pyenv_version_name = true

[docker_context]
symbol = " "
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:sapphire)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
